%YAML:1.0
features:
  - {x:1.4,   y:2.2,  z:-1.1,  yaw:0.0}
  - {x:1.4,   y:1.8,  z:-1.1,  yaw:0.0}
  - {x:1.4,   y:1.4,  z:-1.1,  yaw:0.0}
  - {x:1.4,   y:1.0,  z:-1.1,  yaw:0.0}
  - {x:1.4,   y:0.6,  z:-1.1,  yaw:0.0}

