%YAML:1.0
features:
  - {x:-0.28,   y:4.08,  z:-1.2,  yaw:0.0}
  - {x:-0.28,   y:4.08,  z:-1.2,  yaw:0.0}
  - {x:-0.28,   y:4.08,  z:-1.2,  yaw:0.0}
  - {x:-0.28,   y:4.08,  z:-1.2,  yaw:0.0}
  - {x:-0.28,   y:4.08,  z:-1.2,  yaw:0.0}
  - {x:-0.28,   y:4.08,  z:-1.2,  yaw:0.0}
  - {x:-0.28,   y:4.08,  z:-1.2,  yaw:0.0}
